export const ACTION_TYPES = {
    SET_WALLET_ADDRESS : "SET_WALLET_ADDRESS",
    SET_WALLET_CONNECTED : "SET_WALLET_CONNECTED",
    SET_USER_ACCESS_TOKEN: "SET_USER_ACCESS_TOKEN",
    SET_COMPANY_ACCESS_TOKEN: "SET_COMPANY_ACCESS_TOKEN",
    SET_PROFILE_TAB_OPTION: "SET_PROFILE_TAB_OPTION",
    SET_USER:"SET_USER",
}